// Placeholder data in case API fails
const placeholderStoreData = [
  // Regular eggs
  {
    id: "walmart-regular",
    storeId: "walmart",
    name: "WALMART",
    price: 2.28,
    date: "3/10/2025",
    change: -0.17,
    changePercent: -6.9,
    eggType: "REGULAR",
  },
  {
    id: "kroger-regular",
    storeId: "kroger",
    name: "KROGER",
    price: 3.49,
    date: "3/10/2025",
    change: 0.05,
    changePercent: 1.4,
    eggType: "REGULAR",
  },
  {
    id: "target-regular",
    storeId: "target",
    name: "TARGET",
    price: 3.59,
    date: "3/10/2025",
    change: 0.1,
    changePercent: 2.9,
    eggType: "REGULAR",
  },
  {
    id: "wholefoods-regular",
    storeId: "wholefoods",
    name: "WHOLE FOODS",
    price: 4.29,
    date: "3/10/2025",
    change: 0.15,
    changePercent: 3.6,
    eggType: "REGULAR",
  },
  {
    id: "traderjoes-regular",
    storeId: "traderjoes",
    name: "TRADER JOE'S",
    price: 3.99,
    date: "3/10/2025",
    change: 0.0,
    changePercent: 0.0,
    eggType: "REGULAR",
  },
  {
    id: "aldi-regular",
    storeId: "aldi",
    name: "ALDI",
    price: 2.89,
    date: "3/10/2025",
    change: -0.1,
    changePercent: -3.3,
    eggType: "REGULAR",
  },
  {
    id: "publix-regular",
    storeId: "publix",
    name: "PUBLIX",
    price: 3.79,
    date: "3/10/2025",
    change: 0.2,
    changePercent: 5.6,
    eggType: "REGULAR",
  },
  {
    id: "safeway-regular",
    storeId: "safeway",
    name: "SAFEWAY",
    price: 3.69,
    date: "3/10/2025",
    change: 0.0,
    changePercent: 0.0,
    eggType: "REGULAR",
  },
  {
    id: "wegmans-regular",
    storeId: "wegmans",
    name: "WEGMANS",
    price: 3.49,
    date: "3/10/2025",
    change: -0.2,
    changePercent: -5.4,
    eggType: "REGULAR",
  },
  {
    id: "shoprite-regular",
    storeId: "shoprite",
    name: "SHOPRITE",
    price: 3.29,
    date: "3/10/2025",
    change: 0.1,
    changePercent: 3.1,
    eggType: "REGULAR",
  },
  // Add more stores for regular eggs
  {
    id: "albertsons-regular",
    storeId: "albertsons",
    name: "ALBERTSONS",
    price: 3.59,
    date: "3/10/2025",
    change: 0.05,
    changePercent: 1.4,
    eggType: "REGULAR",
  },
  {
    id: "heb-regular",
    storeId: "heb",
    name: "H-E-B", // Updated to H-E-B
    price: 3.39,
    date: "3/10/2025",
    change: -0.1,
    changePercent: -2.9,
    eggType: "REGULAR",
  },
  {
    id: "meijer-regular",
    storeId: "meijer",
    name: "MEIJER",
    price: 3.29,
    date: "3/10/2025",
    change: 0.0,
    changePercent: 0.0,
    eggType: "REGULAR",
  },
  {
    id: "sprouts-regular",
    storeId: "sprouts",
    name: "SPROUTS",
    price: 3.99,
    date: "3/10/2025",
    change: 0.15,
    changePercent: 3.9,
    eggType: "REGULAR",
  },
  {
    id: "food4less-regular",
    storeId: "food4less",
    name: "FOOD 4 LESS",
    price: 2.99,
    date: "3/10/2025",
    change: -0.05,
    changePercent: -1.6,
    eggType: "REGULAR",
  },
  {
    id: "erewhon-regular",
    storeId: "erewhon",
    name: "EREWHON",
    price: 5.99,
    date: "3/10/2025",
    change: 0.0,
    changePercent: 0.0,
    eggType: "REGULAR",
  },
  {
    id: "foodlion-regular",
    storeId: "foodlion",
    name: "FOOD LION",
    price: 3.19,
    date: "3/10/2025",
    change: -0.1,
    changePercent: -3.0,
    eggType: "REGULAR",
  },
  {
    id: "gianteagle-regular",
    storeId: "gianteagle",
    name: "GIANT EAGLE",
    price: 3.49,
    date: "3/10/2025",
    change: 0.1,
    changePercent: 2.9,
    eggType: "REGULAR",
  },
  {
    id: "ralphs-regular",
    storeId: "ralphs",
    name: "RALPHS",
    price: 3.59,
    date: "3/10/2025",
    change: 0.05,
    changePercent: 1.4,
    eggType: "REGULAR",
  },
  {
    id: "stopandshop-regular",
    storeId: "stopandshop",
    name: "STOP & SHOP",
    price: 3.39,
    date: "3/10/2025",
    change: -0.1,
    changePercent: -2.9,
    eggType: "REGULAR",
  },
  {
    id: "vons-regular",
    storeId: "vons",
    name: "VONS",
    price: 3.69,
    date: "3/10/2025",
    change: 0.0,
    changePercent: 0.0,
    eggType: "REGULAR",
  },
  {
    id: "winndixie-regular",
    storeId: "winndixie",
    name: "WINN-DIXIE",
    price: 3.29,
    date: "3/10/2025",
    change: -0.05,
    changePercent: -1.5,
    eggType: "REGULAR",
  },
  {
    id: "weismarkets-regular",
    storeId: "weismarkets",
    name: "WEIS MARKETS",
    price: 3.49,
    date: "3/10/2025",
    change: -0.05,
    changePercent: -1.4,
    eggType: "REGULAR",
  },
  {
    id: "harristeeter-regular",
    storeId: "harristeeter",
    name: "HARRIS TEETER",
    price: 3.69,
    date: "3/10/2025",
    change: 0.1,
    changePercent: 2.8,
    eggType: "REGULAR",
  },

  // Organic eggs
  {
    id: "walmart-organic",
    storeId: "walmart",
    name: "WALMART",
    price: 4.98,
    date: "3/10/2025",
    change: -0.22,
    changePercent: -4.2,
    eggType: "ORGANIC",
  },
  {
    id: "kroger-organic",
    storeId: "kroger",
    name: "KROGER",
    price: 5.99,
    date: "3/10/2025",
    change: 0.0,
    changePercent: 0.0,
    eggType: "ORGANIC",
  },
  {
    id: "target-organic",
    storeId: "target",
    name: "TARGET",
    price: 5.89,
    date: "3/10/2025",
    change: -0.1,
    changePercent: -1.7,
    eggType: "ORGANIC",
  },
  {
    id: "wholefoods-organic",
    storeId: "wholefoods",
    name: "WHOLE FOODS",
    price: 6.99,
    date: "3/10/2025",
    change: 0.0,
    changePercent: 0.0,
    eggType: "ORGANIC",
  },
  {
    id: "traderjoes-organic",
    storeId: "traderjoes",
    name: "TRADER JOE'S",
    price: 5.49,
    date: "3/10/2025",
    change: -0.5,
    changePercent: -8.3,
    eggType: "ORGANIC",
  },
  {
    id: "aldi-organic",
    storeId: "aldi",
    name: "ALDI",
    price: 4.89,
    date: "3/10/2025",
    change: -0.1,
    changePercent: -2.0,
    eggType: "ORGANIC",
  },
  {
    id: "publix-organic",
    storeId: "publix",
    name: "PUBLIX",
    price: 6.29,
    date: "3/10/2025",
    change: 0.0,
    changePercent: 0.0,
    eggType: "ORGANIC",
  },
  {
    id: "safeway-organic",
    storeId: "safeway",
    name: "SAFEWAY",
    price: 6.19,
    date: "3/10/2025",
    change: -0.3,
    changePercent: -4.6,
    eggType: "ORGANIC",
  },
  {
    id: "wegmans-organic",
    storeId: "wegmans",
    name: "WEGMANS",
    price: 5.79,
    date: "3/10/2025",
    change: -0.2,
    changePercent: -3.3,
    eggType: "ORGANIC",
  },
  {
    id: "shoprite-organic",
    storeId: "shoprite",
    name: "SHOPRITE",
    price: 5.99,
    date: "3/10/2025",
    change: 0.0,
    changePercent: 0.0,
    eggType: "ORGANIC",
  },
  // Add more stores for organic eggs
  {
    id: "albertsons-organic",
    storeId: "albertsons",
    name: "ALBERTSONS",
    price: 6.29,
    date: "3/10/2025",
    change: 0.1,
    changePercent: 1.6,
    eggType: "ORGANIC",
  },
  {
    id: "heb-organic",
    storeId: "heb",
    name: "H-E-B", // Updated to H-E-B
    price: 5.89,
    date: "3/10/2025",
    change: -0.2,
    changePercent: -3.3,
    eggType: "ORGANIC",
  },
  {
    id: "meijer-organic",
    storeId: "meijer",
    name: "MEIJER",
    price: 5.79,
    date: "3/10/2025",
    change: 0.0,
    changePercent: 0.0,
    eggType: "ORGANIC",
  },
  {
    id: "sprouts-organic",
    storeId: "sprouts",
    name: "SPROUTS",
    price: 6.49,
    date: "3/10/2025",
    change: 0.2,
    changePercent: 3.2,
    eggType: "ORGANIC",
  },
  {
    id: "food4less-organic",
    storeId: "food4less",
    name: "FOOD 4 LESS",
    price: 5.49,
    date: "3/10/2025",
    change: -0.1,
    changePercent: -1.8,
    eggType: "ORGANIC",
  },
  {
    id: "erewhon-organic",
    storeId: "erewhon",
    name: "EREWHON",
    price: 8.99,
    date: "3/10/2025",
    change: 0.0,
    changePercent: 0.0,
    eggType: "ORGANIC",
  },
  {
    id: "foodlion-organic",
    storeId: "foodlion",
    name: "FOOD LION",
    price: 5.69,
    date: "3/10/2025",
    change: -0.2,
    changePercent: -3.4,
    eggType: "ORGANIC",
  },
  {
    id: "gianteagle-organic",
    storeId: "gianteagle",
    name: "GIANT EAGLE",
    price: 5.99,
    date: "3/10/2025",
    change: 0.1,
    changePercent: 1.7,
    eggType: "ORGANIC",
  },
  {
    id: "ralphs-organic",
    storeId: "ralphs",
    name: "RALPHS",
    price: 6.19,
    date: "3/10/2025",
    change: 0.1,
    changePercent: 1.6,
    eggType: "ORGANIC",
  },
  {
    id: "stopandshop-organic",
    storeId: "stopandshop",
    name: "STOP & SHOP",
    price: 5.89,
    date: "3/10/2025",
    change: -0.15,
    changePercent: -2.5,
    eggType: "ORGANIC",
  },
  {
    id: "vons-organic",
    storeId: "vons",
    name: "VONS",
    price: 6.29,
    date: "3/10/2025",
    change: 0.0,
    changePercent: 0.0,
    eggType: "ORGANIC",
  },
  {
    id: "winndixie-organic",
    storeId: "winndixie",
    name: "WINN-DIXIE",
    price: 5.79,
    date: "3/10/2025",
    change: -0.1,
    changePercent: -1.7,
    eggType: "ORGANIC",
  },
  {
    id: "weismarkets-organic",
    storeId: "weismarkets",
    name: "WEIS MARKETS",
    price: 5.99,
    date: "3/10/2025",
    change: -0.1,
    changePercent: -1.6,
    eggType: "ORGANIC",
  },
  {
    id: "harristeeter-organic",
    storeId: "harristeeter",
    name: "HARRIS TEETER",
    price: 6.29,
    date: "3/10/2025",
    change: 0.15,
    changePercent: 2.4,
    eggType: "ORGANIC",
  },
]

